In [1]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings

import plotly.offline as py
py.init_notebook_mode(connected=True)
import plotly.graph_objs as go
import plotly.tools as tls

from plotly.tools import FigureFactory as FF

import dash
from dash.dependencies import Input, Output
import dash_core_components as dcc
import dash_html_components as html

import flask
import pandas as pd
import time
import os

In [2]:
warnings.filterwarnings("ignore")
%matplotlib inline

In [3]:
crimes1 = pd.read_csv('01_District_wise_crimes_committed_2001_2012.csv')
crimes2 = pd.read_csv('01_District_wise_crimes_committed_2013.csv')

In [4]:
crimes1.isnull().sum()

STATE/UT                                               0
DISTRICT                                               0
YEAR                                                   0
MURDER                                                 0
ATTEMPT TO MURDER                                      0
CULPABLE HOMICIDE NOT AMOUNTING TO MURDER              0
RAPE                                                   0
CUSTODIAL RAPE                                         0
OTHER RAPE                                             0
KIDNAPPING & ABDUCTION                                 0
KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS            0
KIDNAPPING AND ABDUCTION OF OTHERS                     0
DACOITY                                                0
PREPARATION AND ASSEMBLY FOR DACOITY                   0
ROBBERY                                                0
BURGLARY                                               0
THEFT                                                  0
AUTO THEFT                                             0
OTHER THEFT                                            0
RIOTS                                                  0
CRIMINAL BREACH OF TRUST                               0
CHEATING                                               0
COUNTERFIETING                                         0
ARSON                                                  0
HURT/GREVIOUS HURT                                     0
DOWRY DEATHS                                           0
ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY    0
INSULT TO MODESTY OF WOMEN                             0
CRUELTY BY HUSBAND OR HIS RELATIVES                    0
IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES            0
CAUSING DEATH BY NEGLIGENCE                            0
OTHER IPC CRIMES                                       0
TOTAL IPC CRIMES                                       0
dtype: int64

In [5]:
crimes2.isnull().sum()

STATE/UT                                               0
DISTRICT                                               0
YEAR                                                   0
MURDER                                                 0
ATTEMPT TO MURDER                                      0
CULPABLE HOMICIDE NOT AMOUNTING TO MURDER              0
RAPE                                                   0
CUSTODIAL RAPE                                         0
OTHER RAPE                                             0
KIDNAPPING & ABDUCTION                                 0
KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS            0
KIDNAPPING AND ABDUCTION OF OTHERS                     0
DACOITY                                                0
PREPARATION AND ASSEMBLY FOR DACOITY                   0
ROBBERY                                                0
BURGLARY                                               0
THEFT                                                  0
AUTO THEFT                                             0
OTHER THEFT                                            0
RIOTS                                                  0
CRIMINAL BREACH OF TRUST                               0
CHEATING                                               0
COUNTERFIETING                                         0
ARSON                                                  0
HURT/GREVIOUS HURT                                     0
DOWRY DEATHS                                           0
ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY    0
INSULT TO MODESTY OF WOMEN                             0
CRUELTY BY HUSBAND OR HIS RELATIVES                    0
IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES            0
CAUSING DEATH BY NEGLIGENCE                            0
OTHER IPC CRIMES                                       0
TOTAL IPC CRIMES                                       0
dtype: int64

In [6]:
crimes2 =crimes2.replace('ZZ TOTAL', 'TOTAL')

In [7]:
crimes1 =crimes1.replace('DELHI UT TOTAL', 'TOTAL')

In [8]:
#crimes1 =crimes1.replace('D & N HAVELI', 'D&N Haveli')
#crimes1 =crimes1.replace('A & N ISLANDS', 'A&N Islands')
#crimes1['STATE/UT'].lower()

In [9]:
Total_crime = pd.concat([crimes1,crimes2],  ignore_index=False, axis=0)

In [10]:
Total_crime.shape

(9840, 33)

In [11]:
Total_crime.rename(columns={'STATE/UT':'state'}, inplace=True)

states = Total_crime.state.unique()


for i in range(0, len(states)):
    states[i] = states[i].lower()
    
for j in range(0, len(states)):
    if states[j] == 'a & n islands':
       states[j] = 'a&n islands'
    
    if  states[j] == 'd & n haveli':
        states[j] = 'd&n haveli'
      

states = np.unique(states).tolist()

print(states)

['a&n islands', 'andhra pradesh', 'arunachal pradesh', 'assam', 'bihar', 'chandigarh', 'chhattisgarh', 'd&n haveli', 'daman & diu', 'delhi ut', 'goa', 'gujarat', 'haryana', 'himachal pradesh', 'jammu & kashmir', 'jharkhand', 'karnataka', 'kerala', 'lakshadweep', 'madhya pradesh', 'maharashtra', 'manipur', 'meghalaya', 'mizoram', 'nagaland', 'odisha', 'puducherry', 'punjab', 'rajasthan', 'sikkim', 'tamil nadu', 'tripura', 'uttar pradesh', 'uttarakhand', 'west bengal']

In [12]:
Total_crime['state'] = Total_crime['state'].str.lower()
Total_crime.head(3)

,state,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,...,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES
0,andhra pradesh,ADILABAD,2001,101,60,17,50,0,50,46,...,30,1131,16,149,34,175,0,181,1518,4154
1,andhra pradesh,ANANTAPUR,2001,151,125,1,23,0,23,53,...,69,1543,7,118,24,154,0,270,754,4125
2,andhra pradesh,CHITTOOR,2001,101,57,2,27,0,27,59,...,38,2088,14,112,83,186,0,404,1262,5818

In [13]:

Total_crimes= Total_crime[Total_crime['DISTRICT'] == 'TOTAL']

In [14]:
Total_crimes.shape

(455, 33)

In [15]:
Total_crimes.columns

Index(['state', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'OTHER RAPE', 'KIDNAPPING & ABDUCTION',
       'KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS',
       'KIDNAPPING AND ABDUCTION OF OTHERS', 'DACOITY',
       'PREPARATION AND ASSEMBLY FOR DACOITY', 'ROBBERY', 'BURGLARY', 'THEFT',
       'AUTO THEFT', 'OTHER THEFT', 'RIOTS', 'CRIMINAL BREACH OF TRUST',
       'CHEATING', 'COUNTERFIETING', 'ARSON', 'HURT/GREVIOUS HURT',
       'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'INSULT TO MODESTY OF WOMEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',
       'CAUSING DEATH BY NEGLIGENCE', 'OTHER IPC CRIMES', 'TOTAL IPC CRIMES'],
      dtype='object')

In [16]:
Total_crimes['MURDER']=Total_crimes['MURDER']+Total_crimes['ATTEMPT TO MURDER']+Total_crimes['CULPABLE HOMICIDE NOT AMOUNTING TO MURDER']

Total_crimes['RAPE']=Total_crimes['RAPE']+Total_crimes['CUSTODIAL RAPE']+Total_crimes['OTHER RAPE']

Total_crimes['KIDNAPPING & ABDUCTION']=Total_crimes['KIDNAPPING & ABDUCTION']+Total_crimes['KIDNAPPING AND ABDUCTION OF OTHERS']

Total_crimes['THEFT']=Total_crimes['DACOITY']+Total_crimes['PREPARATION AND ASSEMBLY FOR DACOITY']+Total_crimes['ROBBERY']+Total_crimes['BURGLARY']+Total_crimes['THEFT']+Total_crimes['AUTO THEFT']+Total_crimes['OTHER THEFT']

Total_crimes['CRIMINAL BREACH OF TRUST']=Total_crimes['CRIMINAL BREACH OF TRUST']+Total_crimes['CHEATING']+Total_crimes['COUNTERFIETING']

Total_crimes['KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS']=Total_crimes['KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS']+Total_crimes['DOWRY DEATHS']+Total_crimes['ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY']+Total_crimes['INSULT TO MODESTY OF WOMEN']+Total_crimes['CRUELTY BY HUSBAND OR HIS RELATIVES']+Total_crimes['IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES']

In [17]:
del Total_crimes['ATTEMPT TO MURDER'],Total_crimes['CULPABLE HOMICIDE NOT AMOUNTING TO MURDER']

del Total_crimes['CUSTODIAL RAPE'],Total_crimes['OTHER RAPE']

del Total_crimes['KIDNAPPING AND ABDUCTION OF OTHERS']

del Total_crimes['DACOITY'],Total_crimes['PREPARATION AND ASSEMBLY FOR DACOITY'],Total_crimes['ROBBERY'],Total_crimes['BURGLARY'],Total_crimes['AUTO THEFT'],Total_crimes['OTHER THEFT']

del Total_crimes['CHEATING'],Total_crimes['COUNTERFIETING']

del Total_crimes['DOWRY DEATHS'],Total_crimes['ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY'],Total_crimes['INSULT TO MODESTY OF WOMEN'],Total_crimes['CRUELTY BY HUSBAND OR HIS RELATIVES'],Total_crimes['IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES']

del Total_crimes['TOTAL IPC CRIMES']

Total_crimes.rename(columns={'HURT/GREVIOUS HURT':'Grievous hurt'}, inplace=True)
Total_crimes.rename(columns={'OTHER IPC CRIMES':'Other Crimes'}, inplace=True)
Total_crimes.rename(columns={'KIDNAPPING & ABDUCTION':'Kidnapping'}, inplace=True)
Total_crimes.rename(columns={'CRIMINAL BREACH OF TRUST':'Cheating'}, inplace=True)
Total_crimes.rename(columns={'KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS':'Crime aginst women'}, inplace=True)
Total_crimes.rename(columns={'THEFT':'Theft'}, inplace=True)
Total_crimes.rename(columns={'RAPE':'Rape'}, inplace=True)
Total_crimes.rename(columns={'MURDER':'Murder'}, inplace=True)

In [18]:
#Total_crimes.rename(columns={'ARSON':'Arson'}, inplace=True)
Total_crimes=Total_crimes.replace('a & n islands', 'a&n islands')
Total_crimes=Total_crimes.replace('d & n haveli', 'd&n haveli')

Grouped_crime=Total_crimes.groupby(['state']).sum().reset_index()

In [19]:

del Grouped_crime['YEAR']
Grouped_crime.head()

,state,Murder,Rape,Kidnapping,Crime aginst women,Theft,RIOTS,Cheating,ARSON,Grievous hurt,CAUSING DEATH BY NEGLIGENCE,Other Crimes
0,a&n islands,257,272,127,536,3347,140,366,100,1160,48,4766
1,andhra pradesh,60842,30228,30185,257108,754111,29403,128888,12900,607053,152076,530896
2,arunachal pradesh,1402,1150,1354,1740,15566,376,1174,273,5655,874,8130
3,assam,23799,36230,38338,92777,244091,37392,25805,8711,77354,33269,214029
4,bihar,93425,28504,61772,77383,432251,117027,53492,9169,224941,48674,598947

In [20]:
Grouped_crime.shape

(35, 12)

In [21]:
trace1 = go.Bar(
    x= Grouped_crime["Rape"],
    y=Grouped_crime["state"],
    name='Rape',
    orientation = 'h'
     #marker = dict(
        #color = 'rgba(246, 78, 139, 0.6)')
    )


trace2 = go.Bar(
    y= Grouped_crime["state"],
    x= Grouped_crime["Murder"],
    name='Murder',
    orientation = 'h'
    #marker = dict(
        #color = 'rgba(58, 71, 80, 0.6)')
        
        
)

trace3 = go.Bar(
    y= Grouped_crime["state"],
    x= Grouped_crime["ARSON"],
    name='Arson',
    orientation = 'h'
    #marker =dict(
        #color='rgba(255, 255, 128, 0.9)')
    
        
)


trace4 = go.Bar(
    y= Grouped_crime["state"],
    x= Grouped_crime["RIOTS"],
    name='Riots',
    orientation = 'h'
        
)    
trace5 = go.Bar(
    y= Grouped_crime["state"],
    x= Grouped_crime["Grievous hurt"],
    name='Grevious hurt',
    orientation = 'h'
        
)
trace6 = go.Bar(
    y= Grouped_crime["state"],
    x= Grouped_crime["CAUSING DEATH BY NEGLIGENCE"],
    name='Causing death by negligence',
    orientation = 'h',
    #hovertext: 'loooooooooooooooooooooooooong text label'
    #hoverinfo = 'text',
)
trace7 = go.Bar(
    y= Grouped_crime["state"],
    x= Grouped_crime["Kidnapping"],
    name='kidnapping',
    orientation = 'h',
    marker =dict(
        color='rgba(255, 255, 128, 0.9)')
        
)

    
trace8 = go.Bar(
    y= Grouped_crime["state"],
    x= Grouped_crime["Theft"],
    name='Theft',
    orientation = 'h'
        
)
trace9 = go.Bar(
    y= Grouped_crime["state"],
    x= Grouped_crime["Cheating"],
    name='Cheating',
    orientation = 'h'
        
)
trace10 = go.Bar(
    y= Grouped_crime["state"],
    x= Grouped_crime["Crime aginst women"],
    name='Crime against women',
    orientation = 'h',
    marker = dict(
        color = 'rgba(246, 78, 139, 0.6)')
        
)

    
    
data = [trace1, trace2,trace3,trace4,trace5,trace6,trace7,trace8,trace9,trace10]

    
layout = go.Layout(
    
    
    #bordercolor='#FFFFFF',
    
    barmode='stack',
    
    title='Crimes in Indian States from 2001 to 2013 ',
    titlefont=dict(
            family='Courier New, monospace',
            size=19,
            color='rgba(152, 0, 0, .8)'
        
        ),
    
    yaxis=dict(
    
        tickmode='linear',
       
        categoryorder='array',
         autorange=True,
        range=[0,2000500],
        type='category'
        
        
    ),
    
    
    xaxis=dict(
        title='Number of crimes',
        titlefont=dict(
            family='Courier New, monospace',
          
            size=15,
            color='rgba(152, 0, 0, .8)'
        ),
         
        
       
    ),
    
    annotations=[
        dict(
            x=1.12,
            y=1.05,
            align="right",
            valign="top",
            text='            Crime Types :',
            showarrow=False,
            xref="paper",
            yref="paper",
            xanchor="center",
            yanchor="top"
        )
    ],
    
    autosize=False,
    width=1000,
    height=700,
    margin=go.layout.Margin(
        l=150,
        r=80,
        b=80,
        t=70,
        pad=5
    )
    
)


fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='marker-h-bar')

In [22]:
Grouped_crime.dtypes

state                          object
Murder                          int64
Rape                            int64
Kidnapping                      int64
Crime aginst women              int64
Theft                           int64
RIOTS                           int64
Cheating                        int64
ARSON                           int64
Grievous hurt                   int64
CAUSING DEATH BY NEGLIGENCE     int64
Other Crimes                    int64
dtype: object

In [23]:
police = pd.read_csv('12_Police_strength_actual_and_sanctioned.csv')
recoverd = pd.read_csv('10_Property_stolen_and_recovered.csv')

In [24]:
police.isnull().sum()

Area_Name                             0
Year                                  0
Group_Name                            0
Sub_Group_Name                        0
Rank_All_Ranks_Total                  0
Rank_ASI_Equivalent                   0
Rank_ASPDySPAssttCommandant           0
Rank_Below_HC_and_Above_Constables    0
Rank_Constables                       0
Rank_DGAddl_DG                        0
Rank_DIG                              0
Rank_Head_Constables                  0
Rank_IGSplIG                          0
Rank_Inspectors_Equivalent            0
Rank_SI_Equivalent                    0
Rank_SSPSPAddlSPCommandant            0
dtype: int64

In [25]:
recoverd.isnull().sum()

Area_Name                      0
Year                           0
Group_Name                     0
Sub_Group_Name                 0
Cases_Property_Recovered       0
Cases_Property_Stolen          0
Value_of_Property_Recovered    0
Value_of_Property_Stolen       0
dtype: int64

In [26]:
police= police[(police['Group_Name']== 'Actual Police Strength - Civil Police') |(police['Group_Name']== 'Actual Women Police Strength - Civil Police')]


police =police.replace('Actual Police Strength - Civil Police', 'Civil Police')
police =police.replace('Actual Women Police Strength - Civil Police', 'Women Civil Police')

In [27]:
police.rename(columns={'Area_Name':'STATE/UT'}, inplace=True)
police.rename(columns={'Rank_All_Ranks_Total':'Total'}, inplace=True)
police_grouped=police.groupby(['STATE/UT','Year']).sum().reset_index()

#mke group by with year 

police_grouped_year=police.groupby(['STATE/UT','year']).sum().reset_index()
police_grouped_year.head()

In [28]:
police_grouped.head()

,STATE/UT,Year,Total,Rank_ASI_Equivalent,Rank_ASPDySPAssttCommandant,Rank_Below_HC_and_Above_Constables,Rank_Constables,Rank_DGAddl_DG,Rank_DIG,Rank_Head_Constables,Rank_IGSplIG,Rank_Inspectors_Equivalent,Rank_SI_Equivalent,Rank_SSPSPAddlSPCommandant
0,Andaman & Nicobar Islands,2001,2112,198,9,0,1398,0,1,363,1,25,116,1
1,Andaman & Nicobar Islands,2002,2345,200,14,0,1570,0,0,413,1,30,115,2
2,Andaman & Nicobar Islands,2003,2352,201,11,0,1577,0,0,413,1,30,117,2
3,Andaman & Nicobar Islands,2004,2357,195,10,0,1585,0,0,411,1,31,121,3
4,Andaman & Nicobar Islands,2005,2361,193,11,0,1580,0,1,418,1,31,122,4

In [29]:
#del police_grouped['Year']
del police_grouped['Rank_ASI_Equivalent']
del police_grouped['Rank_ASPDySPAssttCommandant']
del police_grouped['Rank_Below_HC_and_Above_Constables']
del police_grouped['Rank_Constables']
del police_grouped['Rank_DGAddl_DG']
del police_grouped['Rank_DIG']
del police_grouped['Rank_Head_Constables']
del police_grouped['Rank_IGSplIG']
del police_grouped['Rank_Inspectors_Equivalent']
del police_grouped['Rank_SI_Equivalent']
del police_grouped['Rank_SSPSPAddlSPCommandant']

In [30]:
police_grouped.head()

                    STATE/UT  Year  Total
0  Andaman & Nicobar Islands  2001   2112
1  Andaman & Nicobar Islands  2002   2345
2  Andaman & Nicobar Islands  2003   2352
3  Andaman & Nicobar Islands  2004   2357
4  Andaman & Nicobar Islands  2005   2361

In [31]:

recoverd.rename(columns={'Area_Name':'STATE/UT'}, inplace=True)
recoverd_grouped=recoverd.groupby(['STATE/UT','Year']).sum().reset_index()

police_grouped= police_grouped[(police_grouped['Group_Name']== 'Civil Police') ]

In [32]:
police_grouped.dtypes

STATE/UT    object
Year         int64
Total        int64
dtype: object

In [33]:
recoverd_grouped.dtypes

STATE/UT                       object
Year                            int64
Cases_Property_Recovered        int64
Cases_Property_Stolen           int64
Value_of_Property_Recovered     int64
Value_of_Property_Stolen        int64
dtype: object

In [34]:
police_grouped['STATE/UT'] = police_grouped['STATE/UT'].astype(str)
recoverd_grouped['STATE/UT'] = recoverd_grouped['STATE/UT'].astype(str)

police_grouped['Year'] = police_grouped['Year'].astype(str)
recoverd_grouped['Year'] = recoverd_grouped['Year'].astype(str)

In [35]:
recoverd_grouped_merge=recoverd_grouped.merge(police_grouped,how="left")

In [36]:
recoverd_grouped_merge.head()

,STATE/UT,Year,Cases_Property_Recovered,Cases_Property_Stolen,Value_of_Property_Recovered,Value_of_Property_Stolen,Total
0,Andaman & Nicobar Islands,2001,108,286,2384358,6368954,2112.0
1,Andaman & Nicobar Islands,2002,74,220,1333518,3685442,2345.0
2,Andaman & Nicobar Islands,2003,80,256,2003574,6367300,2352.0
3,Andaman & Nicobar Islands,2004,190,350,6140866,10166636,2357.0
4,Andaman & Nicobar Islands,2005,160,344,8404966,523406562,2361.0

In [37]:
#del recoverd_grouped_merge['Year']
recoverd_grouped_merge.rename(columns={'Total':'Total_police'}, inplace=True)

In [38]:
trace0 = go.Scatter(
     y= recoverd_grouped_merge['Cases_Property_Stolen'],
     x= recoverd_grouped_merge['Total_police'],
    name = 'Stolen',
    mode = 'markers',
   marker = dict(
                size = 10,
                color = 'rgba(152, 0, 0, .8)',
                line = dict(
                    width = 2,
                    color = 'rgb(0, 0, 0)'
                )
            )
)
trace1 = go.Scatter(
     y= recoverd_grouped_merge['Cases_Property_Recovered'],
     x= recoverd_grouped_merge['Total_police'],
    name = 'Recoverd',
    mode = 'markers',
   marker = dict(
        size = 10,
        color = ('green'),
        line = dict(
            width = 2,
            color = 'rgb(0, 0, 0)'
        )
    )
)

data = [trace0,trace1]


layout= go.Layout(
    title= 'Police performance for theft crime',
    hovermode= 'closest',
    xaxis= dict(
        title= 'Number of police force',
        ticklen= 5,
        zeroline= False,
        gridwidth= 2,
    ),
    yaxis=dict(
        title= 'Recovered / Stolen cases',
        ticklen= 4,
        gridwidth= 1,
    )
)




fig = dict(data=data, layout=layout)
py.iplot(fig, filename='styled-scatter')

In [39]:
crime1=pd.read_csv('17_Case_reported_and_value_of_property_taken_away_by_place_of_occurrence_2001_2012.csv')
crime1.isnull().sum()

STATE/UT                                                                                   0
YEAR                                                                                       0
Place Of Occurrence                                                                        0
Dacoity (Section 395-398 IPC) - Number of cases registered                                 0
Dacoity (Section 395-398 IPC) - Value Of Property Stolen (in rupees)                       0
Robbery(Section 392-394, 397, 398 IPC) - Number of cases registered                        0
Robbery(Section 392-394, 397, 398 IPC) - Value Of Property Stolen (in rupees)              0
Burglary(Section 449-452, 454, 455, 457-460 IPC) - Number of cases registered              0
Burglary(Section 449-452, 454, 455, 457-460 IPC) - Value Of Property Stolen (in rupees)    0
Theft (Section 379-382 IPC) - Number of cases registered                                   0
Theft (Section 379-382 IPC) - Value Of Property Stolen (in rupees)                         0
dtype: int64

In [40]:
crime1['Total_theft_cases']=crime1['Theft (Section 379-382 IPC) - Number of cases registered']+crime1['Dacoity (Section 395-398 IPC) - Number of cases registered']+crime1['Robbery(Section 392-394, 397, 398 IPC) - Number of cases registered']+crime1['Burglary(Section 449-452, 454, 455, 457-460 IPC) - Number of cases registered']
crime2= crime1.groupby(['STATE/UT','YEAR']).sum().reset_index()

In [41]:
demo=pd.read_csv('08_01_Juvenile_apprehended_state_IPC.csv')

demo.isnull().sum()

STATE/UT                          0
Year                              0
CRIME                             0
Boys 7-12 Years                   0
Girls 7-12 Years                  0
Boys 12-16 Years                  0
Girls 12-16 Years                 0
Boys 16-18 Years                  0
Girls 16-18 Years                 0
Total for boys all Age Groups     0
Total for girls all Age Groups    0
Grand total                       0
dtype: int64

In [42]:
demo.head()

,STATE/UT,Year,CRIME,Boys 7-12 Years,Girls 7-12 Years,Boys 12-16 Years,Girls 12-16 Years,Boys 16-18 Years,Girls 16-18 Years,Total for boys all Age Groups,Total for girls all Age Groups,Grand total
0,Andhra Pradesh,2001,Murder,3,0,7,0,5,0,15,0,15
1,Andhra Pradesh,2001,Attempt to Commit Murder,2,0,0,0,11,0,13,0,13
2,Andhra Pradesh,2001,C H Not amounting to Murder,0,0,0,0,0,0,0,0,0
3,Andhra Pradesh,2001,Rape,2,0,15,0,2,1,19,1,20
4,Andhra Pradesh,2001,Custodial Rape,0,0,0,0,0,0,0,0,0

In [43]:
demo= demo[(demo['CRIME']== 'Auto Theft') | (demo['CRIME']== 'Burglary')|(demo['CRIME']== 'Dacoity')|(demo['CRIME']== 'Other Theft')|(demo['CRIME']== 'Preparation & Assembly for Dacoity')|(demo['CRIME']== 'Robbery')|(demo['CRIME']== 'Theft')]

In [44]:
demo_group= demo.groupby(['STATE/UT']).sum().reset_index()

In [45]:
del demo_group['Total for boys all Age Groups']
del demo_group['Total for girls all Age Groups']
del demo_group['Grand total']

In [46]:
demo_group.head()

,STATE/UT,Year,Boys 7-12 Years,Girls 7-12 Years,Boys 12-16 Years,Girls 12-16 Years,Boys 16-18 Years,Girls 16-18 Years
0,A&N Islands,140385,3,0,44,0,98,0
1,Andhra Pradesh,140385,877,27,5988,145,7308,480
2,Arunachal Pradesh,140385,74,1,377,0,375,0
3,Assam,140385,622,53,2336,187,1649,159
4,Bihar,140385,62,2,808,4,1831,8

In [47]:
trace1 = go.Bar(
    y=demo_group['Boys 7-12 Years'],
    x=demo_group['STATE/UT'],
    name='7-12 Years'
)
trace2 = go.Bar(
    y=demo_group['Boys 12-16 Years'],
    x=demo_group['STATE/UT'],

        name='12-16 Years'

)

trace3 = go.Bar(
    y=demo_group['Boys 16-18 Years'],
    x=demo_group['STATE/UT'],

            name='16-18 Years'

    
)

data = [trace1, trace2,trace3]
layout = go.Layout(
    barmode='group',
    title='Theft Done by Boys under 18 ',
)

fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='grouped-bar')

In [48]:
trace1 = go.Bar(
    y=demo_group['Girls 7-12 Years'],
    x=demo_group['STATE/UT'],
    name='7-12 Years'
)
trace2 = go.Bar(
    y=demo_group['Girls 12-16 Years'],
    x=demo_group['STATE/UT'],

        name='12-16 Years'

)

trace3 = go.Bar(
    y=demo_group['Girls 16-18 Years'],
    x=demo_group['STATE/UT'],

            name='16-18 Years'

    
)

data = [trace1, trace2,trace3]
layout = go.Layout(
    barmode='group',
    title='Theft Done by Girls under 18 ',
)

fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='grouped-bar')

In [49]:
demo_group.rename(columns={'Boys 7-12 Years':'by'}, inplace=True)
demo_group.rename(columns={'Boys 12-16 Years':'bm'}, inplace=True)
demo_group.rename(columns={'Boys 16-18 Years':'bb'}, inplace=True)

In [ ]:

demo_group.rename(columns={'Girls 7-12 Years':'gy'}, inplace=True)
demo_group.rename(columns={'Girls 12-16 Years':'gm'}, inplace=True)
demo_group.rename(columns={'Girls 16-18 Years':'gb'}, inplace=True)

In [ ]:

server = flask.Flask('app')
server.secret_key = os.environ.get('secret_key', 'secret')

df = crime2

app = dash.Dash('app', server=server)

#names = list(STATE/UT.keys())

app.scripts.config.serve_locally = False
dcc._js_dist[0]['external_url'] = 'https://cdn.plot.ly/plotly-basic-latest.min.js'

# Boostrap CSS.
app.css.append_css({'external_url': 'https://codepen.io/amyoshino/pen/jzXypZ.css'}) 

app.layout = html.Div(
    html.Div([
        
        
        
# header 
        html.Div(
            [
                html.H1(children='Monitoring Theft crime by states of India from 2001 to 2012',
                        style={'fontColor': 'blue'},
                        className='ten columns'),
                
                html.Div(children='''
                        This dashboard enable each state to follow up theft crime for different factors and understand the hidden pattern
                        ''',
                       
                        className='nine columns'
                )
            ], className="row"
        ),

        
        
# first menue

        html.Div(
            [
                 dcc.Dropdown(
                id='my-dropdown',
                   #  options=[{'label':name, 'value':name} for name in names],
                    # value = list(fnameDict.keys())[0]
               options=[
                                    {'label': 'Assam', 'value': 'Assam'},
                                    {'label': 'Andhra Pradesh', 'value': 'Andhra Pradesh'},
                                    {'label': 'Arunachal Pradesh', 'value': 'Arunachal Pradesh'},
                                    {'label': 'Bihar', 'value': 'Bihar'},
                                    {'label': 'Chandigarh', 'value': 'Chandigarh'},
                                    {'label': 'Goa', 'value': 'Goa'},
                                    {'label': 'Gujarat', 'value': 'Gujarat'},
                                    {'label': 'Haryana', 'value': 'Haryana'},
                                    {'label': 'Himachal Pradesh', 'value': 'Himachal Pradesh'},
                                    {'label': 'Jammu & Kashmir', 'value': 'Jammu & Kashmir'},
                                    {'label': 'Jharkhand', 'value': 'Jharkhand'},
                                    {'label': 'Karnataka', 'value': 'Karnataka'},
                                    {'label': 'Kerala', 'value': 'Kerala'},
                                    {'label': 'Lakshadweep', 'value': 'Lakshadweep'},
                                    {'label': 'Madhya Pradesh', 'value': 'Madhya Pradesh'},
                                    {'label': 'Maharashtra', 'value': 'Maharashtra'},
                                    {'label': 'Manipur', 'value': 'Manipur'},
                                    {'label': 'Meghalaya', 'value': 'Meghalaya'},
                                    {'label': 'Mizoram', 'value': 'Mizoram'},
                                    {'label': 'Nagaland', 'value': 'Nagaland'},
                                    {'label': 'Odisha', 'value': 'Odisha'},
                                    {'label': 'Puducherry', 'value': 'Puducherry'},
                                    {'label': 'Punjab', 'value': 'Punjab'},
                                    {'label': 'Rajasthan', 'value': 'Rajasthan'},
                                    {'label': 'Sikkim', 'value': 'Sikkim'},
                                    {'label': 'Tamil Nadu', 'value': 'Tamil Nadu'},
                                    {'label': 'Tripura', 'value': 'Tripura'},
                                    {'label': 'Uttar Pradesh', 'value': 'Uttar Pradesh'},
                                    {'label': 'Uttarakhand', 'value': 'Uttarakhand'},
                                    {'label': 'West Bengal', 'value': 'West Bengal'},
                                    
                                    

                                        ],

                value='Assam'
            )
            ], className="row"
        ),
        
        
        
        
        
        
# first grapg

                html.Div(
                    [
                     dcc.Graph(
                                id='example-graph-11'
                            )
                    ], className="row"
                ),

               

        
# second grapg       
                html.Div([
                            dcc.Graph(
                                id='example-graph-12'
                            )

                    ], className="row"
                ),
    
 
         
 
    
#third graph

                html.Div([html.Div([
                                        dcc.Graph(
                                            id='example-graph-13'
                                        )

                                ], className= 'six columns'
                            ),
                          
                          html.Div([
                                        dcc.Graph(
                                            id='example-graph-14'
                                        )

                                ], className= 'six columns'
                            )

                                ], className="row"
                            )

    
    
    
  ], className='ten columns offset-by-one')
)




# first grapg callback 

@app.callback(Output('example-graph-11', 'figure'),
              [Input('my-dropdown', 'value')])

def update_graph(selected_dropdown_value):
    dff = df[df['STATE/UT'] == selected_dropdown_value]


    return {
                 'data': [ go.Scatter(
                    x=dff.YEAR,
                    y=dff.Total_theft_cases,
                    mode = 'lines'

                    )

                  ],


                'layout':go.Layout(

                        title='Theft Crime Trend',
                        font=dict(family='Courier New, monospace',size=20),
                    
                        xaxis=dict(tickmode='linear',

                            categoryorder='array'),
                            

                        yaxis=dict(
                            title= 'number of crimes',
                            rangemode='tozero',
                            autorange=True
                        )
                    )

               }

# second grapg callback 

@app.callback(Output('example-graph-12', 'figure'),
              [Input('my-dropdown', 'value')])

def update_graph(selected_dropdown_value):
    dff = recoverd_grouped_merge[recoverd_grouped_merge['STATE/UT'] == selected_dropdown_value]
    recoverd_grouped_merge['Text'] =recoverd_grouped_merge['Year'] 

    return {
        'data': [go.Scatter(
             y= dff.Cases_Property_Stolen,
             x= dff.Total_police,
            name = 'Stolen',
            mode = 'markers',
            text=recoverd_grouped_merge['Text'],
             marker = dict(
                size = 10,
                color = 'rgba(152, 0, 0, .8)',
                line = dict(
                    width = 2,
                    color = 'rgb(0, 0, 0)'
                )
            )
           
        ),
               go.Scatter(
             y= dff.Cases_Property_Recovered,
             x= dff.Total_police,
            name = 'Recoverd',
            mode = 'markers',
            text=recoverd_grouped_merge['Text'],
            marker = dict(
                size = 10,
               color = ('green'),
                line = dict(
                    width = 2,
                )
            )
        )],
        'layout': go.Layout(
            title= 'Police performance Regarding theft crime',
            font=dict(family='Courier New, monospace', color='#894444',size=20),
    
            hovermode= 'closest',
            xaxis= dict(
                title= 'Number of police force',
               # font=dict(family='Courier New, monospace', size=13, color='#7f7f7f')
              #  ticklen= 5,
               # zeroline= False,
                #gridwidth= 2,
            ),
            yaxis=dict(
                title= 'Registed cases',
                #font=dict(family='Courier New, monospace', size=13, color='#7f7f7f')
                #ticklen= 4,
                #gridwidth= 1,
            )
)
    }

#third callback

@app.callback(Output('example-graph-13', 'figure'),
              [Input('my-dropdown', 'value')])

def update_graph(selected_dropdown_value):
    dff =demo_group[demo_group['STATE/UT'] == selected_dropdown_value]
    
    return {
         'data': [ go.Bar(
                y=dff.by,
               # x=dff.demo_group['STATE/UT'],
                name='7-12 Years'
            ),
                go.Bar(
                y=dff.bm,
              #  x=dff.demo_group['STATE/UT'],

                    name='12-16 Years'

            ),

               go.Bar(
                y=dff.bb,
                #x=dff.demo_group['STATE/UT'],

                        name='16-18 Years'


            ),

          ],
        
        'layout':go.Layout(
                barmode='group',
                title='Theft Done by Boys under 18 ',
                font=dict(family='Courier New, monospace',size=20),
                yaxis=dict(
                    title= 'number of crimes'
                )
            )
        
    }

#forth callback
@app.callback(Output('example-graph-14', 'figure'),
              [Input('my-dropdown', 'value')])

def update_graph(selected_dropdown_value):
    dff = demo_group[demo_group['STATE/UT'] == selected_dropdown_value]
    

    return {
         'data': [ go.Bar(
                y=dff.gy,
                #x=dff.demo_group['STATE/UT'],
                name='7-12 Years'
            ),
                go.Bar(
                y=dff.gm,
                #x=dff.demo_group['STATE/UT'],

                    name='12-16 Years'

            ),

               go.Bar(
                y=dff.gb,
               #x=dff.demo_group['STATE/UT'],

                        name='16-18 Years'


            ),

          ],
        
        'layout':go.Layout(
                barmode='group',
                title='Theft Done by Girls under 18 ',
            font=dict(family='Courier New, monospace',size=20),
                showlegend=False
            )
        
    }





















if __name__ == '__main__':
    app.run_server()

 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [01/Apr/2019 04:53:52] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2019 04:53:53] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2019 04:53:53] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2019 04:53:53] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2019 04:53:53] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2019 04:53:53] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2019 04:53:53] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2019 04:54:07] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2019 04:54:07] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2019 04:54:07] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2019 04:54:08] "POST /_dash-update-component HTTP/1.1" 200 -